export enum EMAIL_SUBJECT {
  PLAID_VERIFICATION = 'Upcoming Plaid Verification',
  UPCOMING_PAYMENT = 'Upcoming Payment',
  UPCOMING_LAST_PAYMENT = 'Upcoming Last Payment',
  INVESTMENT_REJECTED = 'Investment Rejected',
  MANUAL_PROCESSING = 'Manual Processing Of The Investment Request',
  INVESTMENT_REJECTED_BY_BO = 'Investment Rejected By Business Owner',
  LATE_PAYMENT = 'Late Payment',
  PLAID_TOKEN = 'Update Of Plaid Token',
  INVESTMENT_FROM_SURVEY = 'Investment Request From Survey',
  INVALID_REPORTS = 'Invalid Monthly Reports',
  PENALTY_INVALID_TRANSACTION = 'Invalid Transaction Penalty',
  PENALTY_INVALID_TOKEN = 'Invalid Token Penalty',
  MONTHLY_REPORT_PENDING = 'Pending Monthly Report',
}
